### ISSUE TITLE
migrate to @types/webmidi

### ISSUE THREAD

**Issue by JackCA** [chrisguttandin/subscribable-things#45]
Was playing around with this and realized the WebMIDI types are written by hand. Check out [@types/webmidi](https://www.npmjs.com/package/@types/webmidi)

:peace_symbol:

**Comment by chrisguttandin** [comment]
Hi Jack, thanks for giving this library a try.

Did you run into any issues with the Web MIDI types? My intention to hand-craft the types was to allow this library to be used without installing some additional types.

I thought that using `@types/webmidi` means that every user of this library needs to install `@types/webmidi` alongside `subscribable-things`. Possibly even in projects which don't use the Web MIDI related functions.

Do you know if it's possible to use `@types/webmidi` without making it an implicit peer dependency?

**Comment by JackCA** [comment]
Oh right, didn't think about the fact that this is used for things outside of web midi.

I think as a dev dependency, it shouldn't be a big deal, but I get what you mean.

The issue only arises if you are using the `@types/webmidi` and are using it elsewhere (e.g. the `MIDIAccess` object) and even then you can use `midiAccess as IMIDIAccess`

Feel free to close if you want to stick with the custom types :)

**Comment by chrisguttandin** [comment]
After taking a closer look at the types of `@types/webmidi` I would not recommend using them together with this library.

The differences are that the `on...` event handler properties of `@types/webmidi` are incomplete and the event handlers itself do not support generics.

```js
midiInput.onmidimessage = (event) => {
    event.port // This is a MIDIPort with @types/webmidi.
               // It's the same type as midiInput with subscribable-things.
};
```

If you want to add the types for the `requestMIDIAccess()` function you could create a .d.ts file which looks somehow like this:

```typescript
import { IMidiAccess } from 'subscribable-things';

interface Navigator {
    requestMIDIAccess?: (options?: { sysex: boolean }) => Promise<IMidiAccess>;
}
```

I hope this helps. Please let me know if you run into any further issues or incompatibilities.

**Comment by JackCA** [comment]
It does help, and sorry for the misdirection.

This solution works for me
