### ISSUE TITLE
hashchange / even source?

### ISSUE THREAD

**Issue by dy** [chrisguttandin/subscribable-things#73]
Found myself implementing wrapper for `hashchange` event as:

```js
import ref from 'value-ref'
const hash = ref(window.location.hash || '#/')
window.addEventListener('hashchange', e => hash(window.location.hash))
hash.subscribe(...)
```

Does it make sense to provide hash source? Or mb location? Probably it's vast topic.

```js
import hash from 'subscribable-sources'
hash.subscribe(...)
```
?

**Comment by chrisguttandin** [comment]
Hi Dmitry,

there is already a generic function for listening to events.

Here is the part in the README that talks about it: https://github.com/chrisguttandin/subscribable-things#ontarget-eventtarget-type-string-options-boolean--addeventlisteneroptions-subscribablethingevent.

Here is the integration test which probably documents it better: https://github.com/chrisguttandin/subscribable-things/blob/a1aa54a327d2543545af03e2fad3bcc216d2361e/test/integration/on.js#L115-L134

Does that help with your use case?

**Comment by chrisguttandin** [comment]
Thanks a lot for your suggestion. I just updated the README. https://github.com/chrisguttandin/subscribable-things/commit/41983a368f1936fbd349595d632126f442ea0d77 It looks much better now.

I'm not sure about adding a `.map()` function. If we do so then someone might ask for a `.filter()` function next and at some point we end up with a lot of operators which will bloat the bundle for everyone.

Currently the `map()` operator isn't even public. It's just a test helper for now. https://github.com/chrisguttandin/subscribable-things/blob/41983a368f1936fbd349595d632126f442ea0d77/test/helpers/map.js

I wonder if there is already a collection of operators that could be reused somehow.

**Comment by dy** [comment]
Looks nice! Yeah, I also doubt about `map`. [Observable proposal discussion](https://github.com/tc39/proposal-observable/issues/210) converges to minimal possible implementation, which makes the most sense.

As for the library - good idea. In github.com/spectjs/value-ref I came to `Ref.from(anyReactiveSource)` method, mimicking `Array.from` for observables. 

But there indeed seems to be missing a small lib for observables with minimal set of operators and reactive sources (value/object/list). Like tiny rxjs, or reactive lodash. Sort less proprietary vue reactivity.

**Comment by chrisguttandin** [comment]
Maybe we could create a package called `pipeable-operators` (the name is still available) which draws some inspiration from RxJS.

It could provide some operators and a `pipe()` function which takes a `SubscribableThing` (or any other standards compliant `Observable`) as a first parameter and a list of operators to apply. The return value would be another `SubscribableThing`.

```js
const newObservable = pipe(
    oldObservable,
    map((value) => value + 2),
    filter((value) => value % 2 === 0)
);
```

Like in RxJS an operator would be a function which takes an `Observable` and returns another one.


But it almost feels unrealistic to me that something like this doesn't exist yet. 🤷‍♂️

**Comment by dy** [comment]
I like the idea, but I think that is [rxjs/operators](https://rxjs.dev/guide/operators) we're talking about, unless there's a point for a separate portable lib with minimal set of indispensable ones. `map`, `filter`, `take`, ... That reminds [mutant](https://github.com/mmckegg/mutant).

Yeah, it can also possibly subscribe to `asyncIterables` as well?

**Comment by dy** [comment]
To the point there is:
* [observable-fns](https://www.npmjs.com/package/observable-fns)
* [observable-operators](https://www.npmjs.com/package/observable-operators)

**Comment by chrisguttandin** [comment]
Thanks for all the links. It looks like it's a solved problem. ;-) Should we then close this issue? Or am I missing something?

**Comment by dy** [comment]
I guess, yes.

**Comment by chrisguttandin** [comment]
Alright, I'm going to close it. Please feel free to open a new issue if you have another idea how this library could be extended or improved.
